import calendar    #give the find the day of the week for any date
m=int(input("Enter the month: "))
d=int(input("Enter the day: "))
y=int(input("Enter the year: "))
day=calendar.weekday(y,m,d)
if day==0:    print("Monday")
elif day==1:    print("Tuesday")
elif day==2:    print("Wednesday")
elif day==3:    print("Thursday")
elif day==4:    print("Friday")
elif day==5:    print("Saturday")
elif day==6:    print("Sunday")